# -*- coding: utf-8 -*-
"""真实手机模型数据定义"""

REAL_PHONES = [
    # === 华为 ===
    {
        "brand": "华为",
        "series": "Mate",
        "model_name": "Mate 60 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.82,
        "screen_resolution": "2720x1260",
        "refresh_rate": 120,
        "processor": "麒麟9000S",
        "camera_main": "5000万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": "4800万",
        "camera_front": "1300万",
        "battery": 5000,
        "charging": "88W快充",
        "weight": 225.0,
        "os": "HarmonyOS",
        "base_price": 6499.0,
        "tags": ["商务", "拍照", "卫星通信", "鸿蒙旗舰"],
        "description": "搭载麒麟9000S处理器，支持双向卫星通话，第二代昆仑玻璃，超可靠玄武架构，超光变XMAGE影像。",
        "release_date": "2023-08-29"
    },
    {
        "brand": "华为",
        "series": "Pura",
        "model_name": "Pura 70 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.8,
        "screen_resolution": "2844x1260",
        "refresh_rate": 120,
        "processor": "麒麟9010",
        "camera_main": "5000万",
        "camera_ultra_wide": "1250万",
        "camera_telephoto": "4800万",
        "camera_front": "1300万",
        "battery": 5050,
        "charging": "100W快充",
        "weight": 220.0,
        "os": "HarmonyOS",
        "base_price": 6499.0,
        "tags": ["拍照", "旗舰", "时尚", "鸿蒙"],
        "description": "全新风向标设计，搭载麒麟9010芯片，超聚光微距长焦，支持100W有线快充，第二代昆仑玻璃。",
        "release_date": "2024-04-18"
    },
    {
        "brand": "华为",
        "series": "Pura",
        "model_name": "Pura 70 Ultra",
        "screen_type": "曲面屏",
        "screen_size": 6.8,
        "screen_resolution": "2844x1260",
        "refresh_rate": 120,
        "processor": "麒麟9010",
        "camera_main": "5000万",
        "camera_ultra_wide": "4000万",
        "camera_telephoto": "5000万",
        "camera_front": "1300万",
        "battery": 5200,
        "charging": "100W快充",
        "weight": 226.0,
        "os": "HarmonyOS",
        "base_price": 9999.0,
        "tags": ["顶级拍照", "伸缩镜头", "旗舰", "卫星通信"],
        "description": "搭载超聚光伸缩主摄，一英寸大底传感器，麒麟9010芯片，支持双卫星通信，星芒纹饰素皮后盖。",
        "release_date": "2024-04-18"
    },
    {
        "brand": "华为",
        "series": "nova",
        "model_name": "nova 12 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.76,
        "screen_resolution": "2776x1224",
        "refresh_rate": 120,
        "processor": "麒麟9000S",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "6000万",
        "battery": 4600,
        "charging": "100W快充",
        "weight": 201.0,
        "os": "HarmonyOS",
        "base_price": 3999.0,
        "tags": ["前置拍照", "轻薄", "高颜值"],
        "description": "搭载麒麟9000S降频版处理器，前置6000万追焦双摄，支持100W智能快充，物理可变光圈主摄。",
        "release_date": "2023-12-26"
    },
    {
        "brand": "华为",
        "series": "Mate",
        "model_name": "Mate X5",
        "screen_type": "折叠屏",
        "screen_size": 7.85,
        "screen_resolution": "2496x2224",
        "refresh_rate": 120,
        "processor": "麒麟9000S",
        "camera_main": "5000万",
        "camera_ultra_wide": "1300万",
        "camera_telephoto": "1200万",
        "camera_front": "800万",
        "battery": 5060,
        "charging": "66W快充",
        "weight": 243.0,
        "os": "HarmonyOS",
        "base_price": 12999.0,
        "tags": ["折叠屏", "商务", "奢华", "鸿蒙旗舰"],
        "description": "超轻薄折叠屏屏旗舰，玄武贴合钢化昆仑玻璃，双向卫星消息，5060mAh高硅负极电池。",
        "release_date": "2023-09-08"
    },

    # === 小米 ===
    {
        "brand": "小米",
        "series": "小米数字",
        "model_name": "小米 14",
        "screen_type": "直屏",
        "screen_size": 6.36,
        "screen_resolution": "2670x1200",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "5000万",
        "camera_front": "3200万",
        "battery": 4610,
        "charging": "90W快充",
        "weight": 193.0,
        "os": "HyperOS",
        "base_price": 3999.0,
        "tags": ["小屏旗舰", "徕卡拍照", "性能狂暴", "直屏首选"],
        "description": "经典小屏旗舰，搭载第三代骁龙8，徕卡Summilux镜头，1.5K高刷超视网膜直屏，90W有线闪充。",
        "release_date": "2023-10-26"
    },
    {
        "brand": "小米",
        "series": "小米数字",
        "model_name": "小米 14 Ultra",
        "screen_type": "曲面屏",
        "screen_size": 6.73,
        "screen_resolution": "3200x1440",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "5000万",
        "camera_front": "3200万",
        "battery": 5300,
        "charging": "90W快充",
        "weight": 220.0,
        "os": "HyperOS",
        "base_price": 6499.0,
        "tags": ["影像机皇", "徕卡四摄", "2K全等深微曲屏", "性能怪兽"],
        "description": "专业影像旗舰，徕卡全焦段四摄，一英寸无级可变光圈主摄，金沙江电池，双向卫星通信。",
        "release_date": "2024-02-22"
    },
    {
        "brand": "小米",
        "series": "Redmi",
        "model_name": "Redmi K70",
        "screen_type": "直屏",
        "screen_size": 6.67,
        "screen_resolution": "3200x1440",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen2",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5000,
        "charging": "120W快充",
        "weight": 209.0,
        "os": "HyperOS",
        "base_price": 2499.0,
        "tags": ["性价比极高", "2K国产直屏", "120W闪充", "性能强悍"],
        "description": "搭载第二代骁龙8，2K国产高端直屏，光影猎人800传感器，120W神仙秒充，金属中框质感越级。",
        "release_date": "2023-11-29"
    },
    {
        "brand": "小米",
        "series": "Redmi",
        "model_name": "Redmi K70 Pro",
        "screen_type": "直屏",
        "screen_size": 6.67,
        "screen_resolution": "3200x1440",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": "5000万",
        "camera_front": "1600万",
        "battery": 5000,
        "charging": "120W快充",
        "weight": 209.0,
        "os": "HyperOS",
        "base_price": 3299.0,
        "tags": ["性能旗舰", "2K直屏", "高能性价比"],
        "description": "搭载第三代骁龙8，Redmi旗舰直屏，光影猎人800，黄金焦段人像镜头，冰封散热系统。",
        "release_date": "2023-11-29"
    },
    {
        "brand": "小米",
        "series": "Redmi",
        "model_name": "Redmi Note 13 Pro",
        "screen_type": "直屏",
        "screen_type_detail": "直屏",
        "screen_size": 6.67,
        "screen_resolution": "2712x1220",
        "refresh_rate": 120,
        "processor": "第二代骁龙7s",
        "camera_main": "2亿",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5100,
        "charging": "67W快充",
        "weight": 187.0,
        "os": "MIUI",
        "base_price": 1399.0,
        "tags": ["千元机", "2亿像素", "高刷屏幕", "护眼直屏"],
        "description": "两亿像素超清主摄，支持OIS光学防抖，第二代骁龙7s移动平台，1.5K金刚护眼直屏，超薄窄边框。",
        "release_date": "2023-09-21"
    },
    {
        "brand": "小米",
        "series": "Redmi",
        "model_name": "Redmi K70E",
        "screen_type": "直屏",
        "screen_size": 6.67,
        "screen_resolution": "2712x1220",
        "refresh_rate": 120,
        "processor": "天玑8300-Ultra",
        "camera_main": "6400万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5500,
        "charging": "90W快充",
        "weight": 198.0,
        "os": "HyperOS",
        "base_price": 1999.0,
        "tags": ["性价比", "长续航", "直屏", "天玑冷芯"],
        "description": "首发联发科天玑8300-Ultra，搭载90W閃充与5500mAh大电池，1.5K直屏，支持狂暴引擎3.0。",
        "release_date": "2023-11-29"
    },

    # === 苹果 ===
    {
        "brand": "苹果",
        "series": "iPhone",
        "model_name": "iPhone 15",
        "screen_type": "直屏",
        "screen_size": 6.1,
        "screen_resolution": "2556x1179",
        "refresh_rate": 60,
        "processor": "A16 Bionic",
        "camera_main": "4800万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": None,
        "camera_front": "1200万",
        "battery": 3349,
        "charging": "20W有线",
        "weight": 171.0,
        "os": "iOS",
        "base_price": 5999.0,
        "tags": ["iOS系统", "灵动岛", "拍照清晰", "彩色玻璃后盖"],
        "description": "搭载A16仿生芯片，采用灵动岛设计，4800万像素主摄，USB-C接口，融色玻璃后盖。",
        "release_date": "2023-09-13"
    },
    {
        "brand": "苹果",
        "series": "iPhone",
        "model_name": "iPhone 15 Pro Max",
        "screen_type": "直屏",
        "screen_size": 6.7,
        "screen_resolution": "2796x1290",
        "refresh_rate": 120,
        "processor": "A17 Pro",
        "camera_main": "4800万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": "1200万",
        "camera_front": "1200万",
        "battery": 4422,
        "charging": "27W有线",
        "weight": 221.0,
        "os": "iOS",
        "base_price": 9999.0,
        "tags": ["iOS旗舰", "钛金属边框", "3nm处理器", "5倍长焦"],
        "description": "首款采用航空级钛金属设计的iPhone，搭载A17 Pro芯片，支持5倍光学变焦，Action Button自定义按键。",
        "release_date": "2023-09-13"
    },
    {
        "brand": "苹果",
        "series": "iPhone",
        "model_name": "iPhone 16 Pro",
        "screen_type": "直屏",
        "screen_size": 6.3,
        "screen_resolution": "2622x1206",
        "refresh_rate": 120,
        "processor": "A18 Pro",
        "camera_main": "4800万",
        "camera_ultra_wide": "4800万",
        "camera_telephoto": "1200万",
        "camera_front": "1200万",
        "battery": 3582,
        "charging": "25W快充",
        "weight": 199.0,
        "os": "iOS",
        "base_price": 7999.0,
        "tags": ["iOS最新", "相机控制按键", "3nm增强", "旗舰单手"],
        "description": "搭载A18 Pro芯片，全新的相机控制键，升级的4800万超广角镜头，支持5倍光学长焦变焦，更大尺寸屏幕。",
        "release_date": "2024-09-10"
    },
    {
        "brand": "苹果",
        "series": "iPhone",
        "model_name": "iPhone 16 Pro Max",
        "screen_type": "直屏",
        "screen_size": 6.9,
        "screen_resolution": "2868x1320",
        "refresh_rate": 120,
        "processor": "A18 Pro",
        "camera_main": "4800万",
        "camera_ultra_wide": "4800万",
        "camera_telephoto": "1200万",
        "camera_front": "1200万",
        "battery": 4685,
        "charging": "30W快充",
        "weight": 227.0,
        "os": "iOS",
        "base_price": 9999.0,
        "tags": ["最强iOS", "大屏天花板", "长效续航", "影像顶级"],
        "description": "顶配iOS机皇，6.9英寸超大屏幕，搭载A18 Pro处理器，超大容量电池，全面融合Apple Intelligence人工智能。",
        "release_date": "2024-09-10"
    },

    # === OPPO ===
    {
        "brand": "OPPO",
        "series": "Find",
        "model_name": "Find X7",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2780x1264",
        "refresh_rate": 120,
        "processor": "天玑9300",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "6400万",
        "camera_front": "3200万",
        "battery": 5000,
        "charging": "100W快充",
        "weight": 206.0,
        "os": "ColorOS",
        "base_price": 3999.0,
        "tags": ["哈苏影像", "天玑双子星", "人像长焦", "高亮屏"],
        "description": "搭载天玑9300旗舰移动平台，哈苏超光影三系统，潮汐架构，6400万超光感潜望长焦。",
        "release_date": "2024-01-08"
    },
    {
        "brand": "OPPO",
        "series": "Find",
        "model_name": "Find X7 Ultra",
        "screen_type": "曲面屏",
        "screen_size": 6.82,
        "screen_resolution": "3168x1440",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "5000万",
        "camera_front": "3200万",
        "battery": 5000,
        "charging": "100W快充",
        "weight": 221.0,
        "os": "ColorOS",
        "base_price": 5999.0,
        "tags": ["双潜望长焦", "哈苏顶级人像", "一英寸大底", "2K曲面屏"],
        "description": "影像天花板，搭载第三代骁龙8处理器，哈苏大师影像，首创双潜望镜长焦系统（3x+6x焦段）。",
        "release_date": "2024-01-08"
    },
    {
        "brand": "OPPO",
        "series": "Reno",
        "model_name": "Reno 11",
        "screen_type": "曲面屏",
        "screen_size": 6.7,
        "screen_resolution": "2412x1080",
        "refresh_rate": 120,
        "processor": "天玑8200",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": "3200万",
        "camera_front": "3200万",
        "battery": 4800,
        "charging": "67W快充",
        "weight": 184.0,
        "os": "ColorOS",
        "base_price": 2499.0,
        "tags": ["轻薄人像", "高颜值后盖", "自拍神器"],
        "description": "黄金单反人像镜头，天玑8200旗舰芯片，轻薄宝石设计手感出色，支持67W超级闪充。",
        "release_date": "2023-11-23"
    },
    {
        "brand": "OPPO",
        "series": "Reno",
        "model_name": "Reno 12",
        "screen_type": "直屏",
        "screen_size": 6.7,
        "screen_resolution": "2412x1080",
        "refresh_rate": 120,
        "processor": "天玑8250",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": "5000万",
        "camera_front": "5000万",
        "battery": 5000,
        "charging": "80W快充",
        "weight": 179.0,
        "os": "ColorOS",
        "base_price": 2699.0,
        "tags": ["等深微四曲屏", "防刮耐摔", "轻薄自拍"],
        "description": "四曲直屏设计，天玑8250星速版，单反级人像三摄，全刚石架构，防摔防溅水。",
        "release_date": "2024-05-23"
    },
    {
        "brand": "OPPO",
        "series": "K",
        "model_name": "K12",
        "screen_type": "直屏",
        "screen_size": 6.7,
        "screen_resolution": "2412x1080",
        "refresh_rate": 120,
        "processor": "第三代骁龙7",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5500,
        "charging": "100W快充",
        "weight": 186.0,
        "os": "ColorOS",
        "base_price": 1799.0,
        "tags": ["千元续航王", "十面耐摔", "超快闪充"],
        "description": "金刚石架构十面耐摔，5500mAh超大长寿电池，长寿版100W闪充，搭载骁龙7 Gen3移动平台。",
        "release_date": "2024-04-24"
    },

    # === vivo ===
    {
        "brand": "vivo",
        "series": "X",
        "model_name": "X100",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2800x1260",
        "refresh_rate": 120,
        "processor": "天玑9300",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "6400万",
        "camera_front": "3200万",
        "battery": 5000,
        "charging": "120W快充",
        "weight": 206.0,
        "os": "OriginOS",
        "base_price": 3999.0,
        "tags": ["蔡司光学", "天玑首发", "潜望长焦", "超级闪充"],
        "description": "首发天玑9300全大核芯片，蔡司超级长焦镜头，自研影像芯片V2，超能大电池，支持IP68防尘防水。",
        "release_date": "2023-11-13"
    },
    {
        "brand": "vivo",
        "series": "X",
        "model_name": "X100 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2800x1260",
        "refresh_rate": 120,
        "processor": "天玑9300",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "5000万",
        "camera_front": "3200万",
        "battery": 5400,
        "charging": "100W快充",
        "weight": 225.0,
        "os": "OriginOS",
        "base_price": 4999.0,
        "tags": ["一英寸主摄", "蔡司APO长焦", "顶级影像旗舰", "长续航"],
        "description": "蔡司全焦段人像，APO潜望长焦，一英寸大底主摄，5400mAh蓝海大电池，蔡司大师色彩。",
        "release_date": "2023-11-13"
    },
    {
        "brand": "vivo",
        "series": "iQOO",
        "model_name": "iQOO 12",
        "screen_type": "直屏",
        "screen_size": 6.78,
        "screen_resolution": "2800x1260",
        "refresh_rate": 144,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "6400万",
        "camera_front": "1600万",
        "battery": 5000,
        "charging": "120W快充",
        "weight": 203.0,
        "os": "OriginOS",
        "base_price": 3999.0,
        "tags": ["电竞直屏", "游戏旗舰", "超级快充", "潜望长焦"],
        "description": "搭载第三代骁龙8，自研电竞芯片Q1，144Hz高刷电竞直屏，支持万里追光影像系统与120W闪充。",
        "release_date": "2023-11-07"
    },
    {
        "brand": "vivo",
        "series": "iQOO",
        "model_name": "iQOO Neo9",
        "screen_type": "直屏",
        "screen_size": 6.78,
        "screen_resolution": "2800x1260",
        "refresh_rate": 144,
        "processor": "骁龙8 Gen2",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5160,
        "charging": "120W快充",
        "weight": 190.0,
        "os": "OriginOS",
        "base_price": 2299.0,
        "tags": ["游戏性价比", "大电池直屏", "极客电竞"],
        "description": "第二代骁龙8处理器，双芯电竞旗舰，IMX920索尼大底主摄，5160mAh蓝海双芯电池，120W闪充。",
        "release_date": "2023-12-27"
    },
    {
        "brand": "vivo",
        "series": "S",
        "model_name": "S18 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2800x1260",
        "refresh_rate": 120,
        "processor": "天玑9200+",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "1200万",
        "camera_front": "5000万",
        "battery": 5000,
        "charging": "80W快充",
        "weight": 187.8,
        "os": "OriginOS",
        "base_price": 3199.0,
        "tags": ["柔光自拍", "神仙颜值", "轻薄旗舰设计"],
        "description": "影棚级柔光环设计，前置5000万超广角柔光镜，搭载天玑9200+旗舰芯片，轻薄手感宛如羊脂白玉。",
        "release_date": "2023-12-14"
    },
    {
        "brand": "vivo",
        "series": "Y",
        "model_name": "Y200",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2400x1080",
        "refresh_rate": 120,
        "processor": "第一代骁龙6",
        "camera_main": "5000万",
        "camera_ultra_wide": "200万",
        "camera_telephoto": None,
        "camera_front": "800万",
        "battery": 6000,
        "charging": "80W快充",
        "weight": 190.0,
        "os": "OriginOS",
        "base_price": 1599.0,
        "tags": ["超长续航", "大电池轻薄", "千元机"],
        "description": "主打6000mAh怪兽级长寿命蓝海电池，轻薄金刚盾机身，80W远航闪充，防尘耐摔。",
        "release_date": "2024-05-20"
    },

    # === 荣耀 ===
    {
        "brand": "荣耀",
        "series": "Magic",
        "model_name": "Magic 6",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2800x1264",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "3200万",
        "camera_front": "5000万",
        "battery": 5450,
        "charging": "66W快充",
        "weight": 206.0,
        "os": "MagicOS",
        "base_price": 4399.0,
        "tags": ["单反级鹰眼相机", "绿洲护眼屏", "巨犀玻璃", "长续航"],
        "description": "第二代青海湖电池（5450mAh），搭载第三代骁龙8，荣耀巨犀玻璃十倍耐摔，荣耀绿洲护眼屏。",
        "release_date": "2024-01-11"
    },
    {
        "brand": "荣耀",
        "series": "Magic",
        "model_name": "Magic 6 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.8,
        "screen_resolution": "2800x1280",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "5000万",
        "camera_telephoto": "1.8亿",
        "camera_front": "5000万",
        "battery": 5600,
        "charging": "80W快充",
        "weight": 229.0,
        "os": "MagicOS",
        "base_price": 5699.0,
        "tags": ["1.8亿像素长焦", "鸿雁卫星通信", "顶级机皇", "青海湖续航"],
        "description": "顶配旗舰，1.8亿像素潜望式长焦，支持荣耀鸿雁双向卫星通信，5600mAh超大青海湖电池，全能机皇。",
        "release_date": "2024-01-11"
    },
    {
        "brand": "荣耀",
        "series": "数字",
        "model_name": "荣耀 100",
        "screen_type": "曲面屏",
        "screen_size": 6.7,
        "screen_resolution": "2664x1200",
        "refresh_rate": 120,
        "processor": "第三代骁龙7",
        "camera_main": "5000万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": None,
        "camera_front": "5000万",
        "battery": 5000,
        "charging": "100W快充",
        "weight": 183.0,
        "os": "MagicOS",
        "base_price": 2299.0,
        "tags": ["单反级写真相机", "高频调光护眼", "个性化后盖"],
        "description": "索尼IMX906单反级写真主摄，首发骁龙7 Gen3移动平台，自研射频增强芯片C1，荣耀绿洲护眼屏。",
        "release_date": "2023-11-23"
    },
    {
        "brand": "荣耀",
        "series": "X",
        "model_name": "荣耀 X50",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2652x1200",
        "refresh_rate": 120,
        "processor": "第一代骁龙6",
        "camera_main": "1.08亿",
        "camera_ultra_wide": "200万",
        "camera_telephoto": None,
        "camera_front": "800万",
        "battery": 5800,
        "charging": "35W快充",
        "weight": 185.0,
        "os": "MagicOS",
        "base_price": 1399.0,
        "tags": ["抗摔之王", "超大电池", "千元机首选"],
        "description": "首个获得瑞士SGS整机五星抗跌耐摔认证，5800mAh超大能量密度电池，一亿像素超清主摄。",
        "release_date": "2023-07-05"
    },
    {
        "brand": "荣耀",
        "series": "X",
        "model_name": "荣耀 X50 GT",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2652x1200",
        "refresh_rate": 120,
        "processor": "骁龙8+ Gen1",
        "camera_main": "1.08亿",
        "camera_ultra_wide": "200万",
        "camera_telephoto": None,
        "camera_front": "800万",
        "battery": 5800,
        "charging": "35W快充",
        "weight": 192.0,
        "os": "MagicOS",
        "base_price": 1999.0,
        "tags": ["强悍性能", "5800mAh长续航", "游戏抗摔", "性价比"],
        "description": "满血版骁龙8+旗舰芯片，5800mAh青海湖大电池，荣耀太极抗摔架构，主打游戏性极高性价比。",
        "release_date": "2024-01-04"
    },

    # === 一加 ===
    {
        "brand": "一加",
        "series": "一加数字",
        "model_name": "一加 12",
        "screen_type": "曲面屏",
        "screen_size": 6.82,
        "screen_resolution": "3168x1440",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "4800万",
        "camera_telephoto": "6400万",
        "camera_front": "3200万",
        "battery": 5400,
        "charging": "100W快充",
        "weight": 220.0,
        "os": "ColorOS",
        "base_price": 4299.0,
        "tags": ["哈苏影像", "顶级2K东方屏", "全能旗舰", "雨水触控"],
        "description": "骁龙8 Gen3，哈苏全焦段三摄（超光影潜望长焦），首发国产2K东方屏，5400mAh超大电池，100W有线+50W无线闪充。",
        "release_date": "2023-12-05"
    },
    {
        "brand": "一加",
        "series": "一加Ace",
        "model_name": "一加 Ace 3",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2780x1264",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen2",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5500,
        "charging": "100W快充",
        "weight": 207.0,
        "os": "ColorOS",
        "base_price": 2599.0,
        "tags": ["性能质感越级", "东方高亮屏", "长寿闪充续航"],
        "description": "搭载骁龙8 Gen2，配备5500mAh大电池+100W快充组合，继承旗舰级东方屏，金属中框质感拉满。",
        "release_date": "2024-01-04"
    },
    {
        "brand": "一加",
        "series": "一加Ace",
        "model_name": "一加 Ace 3 Pro",
        "screen_type": "曲面屏",
        "screen_size": 6.78,
        "screen_resolution": "2780x1264",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 6100,
        "charging": "100W快充",
        "weight": 207.0,
        "os": "ColorOS",
        "base_price": 3199.0,
        "tags": ["冰川电池", "极限性能", "质感机皇", "超跑瓷"],
        "description": "独家冰川电池（6100mAh超大能量），搭载第三代骁龙8，配备100W超级闪充，最高可选24GB运行内存。",
        "release_date": "2024-06-27"
    },
    {
        "brand": "一加",
        "series": "一加Ace",
        "model_name": "一加 Ace 3V",
        "screen_type": "直屏",
        "screen_size": 6.74,
        "screen_resolution": "2772x1240",
        "refresh_rate": 120,
        "processor": "骁龙7+ Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "800万",
        "camera_telephoto": None,
        "camera_front": "1600万",
        "battery": 5500,
        "charging": "100W快充",
        "weight": 200.0,
        "os": "ColorOS",
        "base_price": 1999.0,
        "tags": ["AI手机", "中端真香机", "玻璃后盖直屏"],
        "description": "首发骁龙7+ Gen3芯片，定位「AI普及者」，潮汐架构算法下放，5500mAh大电池，玻璃后盖高质感。",
        "release_date": "2024-03-21"
    },

    # === 三星 ===
    {
        "brand": "三星",
        "series": "Galaxy S",
        "model_name": "Galaxy S24",
        "screen_type": "直屏",
        "model_name_full": "Samsung Galaxy S24",
        "screen_size": 6.2,
        "screen_resolution": "2340x1080",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "5000万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": "1000万",
        "camera_front": "1200万",
        "battery": 4000,
        "charging": "25W快充",
        "weight": 167.0,
        "os": "One UI",
        "base_price": 5499.0,
        "tags": ["小屏旗舰", "Galaxy AI", "超轻量", "屏幕顶级"],
        "description": "极致轻薄单手掌握，6.2英寸顶级AMOLED直屏，Galaxy AI多功能加持（即圈即搜、实时翻译）。",
        "release_date": "2024-01-18"
    },
    {
        "brand": "三星",
        "series": "Galaxy S",
        "model_name": "Galaxy S24 Ultra",
        "screen_type": "直屏",
        "screen_size": 6.8,
        "screen_resolution": "3120x1440",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen3",
        "camera_main": "2亿",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": "5000万",
        "camera_front": "1200万",
        "battery": 5000,
        "charging": "45W快充",
        "weight": 232.0,
        "os": "One UI",
        "base_price": 9699.0,
        "tags": ["机皇天花板", "S Pen手写笔", "钛金属中框", "2亿摄影"],
        "description": "安卓旗舰终极机皇，钛金属机身，平直大屏，支持SPen手写笔，Galaxy AI，超强双长焦拍摄。",
        "release_date": "2024-01-18"
    },
    {
        "brand": "三星",
        "series": "Galaxy Z",
        "model_name": "Galaxy Z Flip5",
        "screen_type": "折叠屏",
        "screen_size": 6.7,
        "screen_resolution": "2640x1080",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen2",
        "camera_main": "1200万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": None,
        "camera_front": "1000万",
        "battery": 3700,
        "charging": "25W快充",
        "weight": 187.0,
        "os": "One UI",
        "base_price": 7499.0,
        "tags": ["小折叠", "时尚外屏", "精致小巧"],
        "description": "竖折叠小屏旗舰，3.4英寸大尺寸外屏丰富玩法，骁龙8 Gen2 for Galaxy，超轻薄零缝隙铰链。",
        "release_date": "2023-07-26"
    },
    {
        "brand": "三星",
        "series": "Galaxy Z",
        "model_name": "Galaxy Z Fold5",
        "screen_type": "折叠屏",
        "screen_size": 7.6,
        "screen_resolution": "2176x1812",
        "refresh_rate": 120,
        "processor": "骁龙8 Gen2",
        "camera_main": "5000万",
        "camera_ultra_wide": "1200万",
        "camera_telephoto": "1000万",
        "camera_front": "1000万",
        "battery": 4400,
        "charging": "25W快充",
        "weight": 253.0,
        "os": "One UI",
        "base_price": 12999.0,
        "tags": ["大折叠屏", "移动办公", "分屏协同"],
        "description": "横折叠移动工作站，7.6英寸沉浸大屏，支持SPen，升级超闭合铰链，多任务处理效率极高。",
        "release_date": "2023-07-26"
    }
]
